[package]
name = "mochi-cli"
description = "Command line indexer for Mochi (milestone 1 deliverable)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "mochi"
path = "src/main.rs"

[dependencies]
mochi-core.workspace = true
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true

[dev-dependencies]
tempfile.workspace = true
